[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "./"  # Use "./" to specify the current directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
